### ISSUE TITLE
create file does not create file

### ISSUE THREAD

**Issue by salimp2009** [liaozixin/nvim-cpptools#1]
Hi, 
thanks for the tool. I just came up to this plugin. 
I installed the plugin and tested creating file. it pops an input prompt and if I enter the name but there is no file 
![image](https://github.com/liaozixin/nvim-cpptools/assets/46407603/56cc7e3e-4853-45da-956f-11c076036b29)

after pressing enter
![image](https://github.com/liaozixin/nvim-cpptools/assets/46407603/e567ca4f-4752-4870-91a8-85815ec7043e)
no file
I am using neovim 0.9.0

**Comment by liaozixin** [comment]
I'm so sorry to see your issue so late！You try closing the nvim-tree file explorer and reopening it.The file should have been created, but it didn't refresh in the browser.

**Comment by salimp2009** [comment]
> I'm so sorry to see your issue so late！You try closing the nvim-tree file explorer and reopening it.The file should have been created, but it didn't refresh in the browser.

thank you replying. I tried again but somehow it does not create a file but also there are no errors either
